language: python
python:
  - 2.7
env:
  global:
  - secure: bpLD2ZHGTXJSPDmIKd4CUsIsF+LSw3ujCRezUPlTP1vo9rQ4ZMN1931gbPpF1EDRoifcecg3+s9BFKPz/7KVEImf59n2WM/iqSmrUm+lf7oGXeGKPZOdTfxH2p7Vg8Y1qAgGrIEFvF0mTEn5DxRMqcwcs8lWVtAAUsJmmuGhkXBkBHLpvpOOjVBcG7tbHFp5WIFRPOEqrCNNIa7pN3OxW1Hi7lMsu/m8g1j+SKVn67m6pas75IthuJJv/IYYAMVA8pcIMLFfVulBnDLin5OrJfOr/DHzicF5CYC2kPDpgMgEh6YtEdycA7o9z49/6rPqJnSZiG208SzBS+M8WFhAuk5sZMVSdzddkp3X4YB0TVTzdGisiUXIXHZOp7To4jE69reQ/CoEegy63WZ1h9ZaUl7M6p0aYJMq4Zes6KMOB4rlx/abBkpXdMQPGNAy/4sHUM9N8dfj0VufgIdZ676eq2QYCLM5LkmJF30SPq6zci/ybBd/O2Uu4O8PtWhEOp/B9pD5InfU9vNQ83rj6mus+PLYfrp9WQrL36ZB1cxtAGRuYmFHe07LT9AdtHQH9CezhNFoZAzm17Q5QTBXWdDgTCQgIFnzpAQx6q5tU4d/mOzitdq4I9+szsmUoVUF+oMoVowtWXChTQSwOEJqArsd18DqKCard/JOG7I5g7ZlQes=
  - secure: M3CWPJXZXWm6Xj5gFrpjGt4iuwajsjOr32k8A4pIIllBWYAtdjZpP59LFEulV7jkJPY9cLhruPbWGEtoYRBQNofMbCuwHmRRvwDHZ06AJoE/1ezdz4e+WwjJDdzE9qu1EtYk5JFoodnz6iEuPn/VaRkrd+ax6LjlyJKulwAJyEB3NDaU5DIL63t3h3yvBLgnNXJ1NaYnU1AABwFfd2fbfjzZzq3eb7Qkpo6Zq8sGwjWBHnB7qizo0o4zlbgOMzNgYI9Mm/doaOGnOSvLAr8vuZ9U86y0jR+jINJibx0nue7nikFYgu++Ba9qz/uE0aX1jLVIUeCzm5qS/vlNrbZb/d0PHL+/HrAWpgqkNMNDpqPw4xq124VimIjJatXfVI9fQw6/nOyCxjcZ/n7/l8tBVAeOlVaKLVfVgBUnfvRsynFJSSxRkf3z3DwqgkBkbC7m3ReEGu5Esb8cTJKtp508nFZqUZfHyEbyrqn2Rl74HlW3JL8QjZ4mDYnQFzVYzdS7faGcoNILaya9jIttFrJTH8NMHSu/2O762rBX35ErCJucSq6ple3X4dpFI/wlbr0UQc187E3fWWaUxrPSk1fg1vgLqnZ00gFz+Xt78bVvezBPhFs4SbvRpUuy1EjQ2+ub8BZM7D4rGgAujtbUnn6sQ+0w4cHGoHuUUf0nAZcMnWE=
  - DATABASE_URL: postgresql://postgres:@localhost/haukka_test
services:
  - postgresql
addons:
  postgresql: "9.4"
install:
  - pip install -q -r requirements.txt
before_script:
  - psql -c 'create database haukka_test;' -U postgres
script:
  - py.test tests
