"""empty message

Revision ID: 24eaaaa1e7e4
Revises: None
Create Date: 2015-07-30 22:42:18.242000

"""

# revision identifiers, used by Alembic.
revision = '24eaaaa1e7e4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trials',
    sa.Column('nctid', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('trial_data', postgresql.JSON(), nullable=True),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('ner_result', postgresql.JSON(), nullable=True),
    sa.Column('lastchanged_date', sa.DateTime(), nullable=True),
    sa.Column('loaded_on', sa.DateTime(), nullable=True),
    sa.Column('processed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nctid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trials')
    ### end Alembic commands ###
